---
- name: create users using loop
  hosts: all
  tasks:
    - name: create users
      user:
         name: "{{ item.name }}"
         state: present
         groups: "{{ item.groups }}"
      loop:
        - name: anna
          groups: wheel
        - name: linda
          groups: users
        - name: bob
          groups: users
