---
- name: create a file
  hosts: all
  tasks:
      - name: create a file
        file:
          path: /tmp/removename
          owner: ansibleuser
          mode: 0640
          state: touch
          setype: public_content_rw_t
